<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>0.0.39</Version>
    <Copyright>2021 Dmitriy Rokoth</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Rokoth/TaskCollector</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Rokoth/TaskCollector</RepositoryUrl>
    <Description>Сервисные классы приложения</Description>
    <RepositoryType>git</RepositoryType>
    <Company>Dmitriy Rokoth</Company>
    <Authors>Dmitriy Rokoth</Authors>
    <Product>TaskCollector</Product>
    <PackageId>TaskCollector.Service</PackageId>
    <Title>Сбор требований. Библиотека бизнес-логики</Title>
    <AssemblyName>TaskCollector.Service</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Contract\Contract.csproj" />
    <ProjectReference Include="..\Db\Db.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
